### ISSUE TITLE
Page jumps when dragging while zooming

### ISSUE THREAD

**Issue by skyfighteer** [rokobuljan/pan-zoom-area#2] opened 2022-12-13 12:58 UTC
When the scaling transition is active (250ms), translating (moving) the canvas will jump the image after the transition is done.

**Comment by rokobuljan** [comment] 2022-12-13 13:13
@skyfighteer  I was able to replicate. using the mouse (drag + scale).  
(On a touch screen, drag + pinch works as expected since there's no transition duration.)
Do you think users will ever use the scaling while panning using the mouse?  

The issue is in that:
zooming requires **both** `scale` and `translate`.  
panning requires `translate`

While scaling the transition duration of 250 will be set to both style.scale and style.translate and as such that timing will be reflected into the panning.

**Comment by skyfighteer** [comment] 2022-12-13 20:08
This is a tough one indeed.
To answer your first question: probably no. Still, it is a bug I immediately thought would occur when you released it, because it is so tricky to get this right...

I hardly have any idea. Maybe the either the panning or the zooming should use transform-origin instead of translate if possible.

I've also seen some people 'faking' the transition through JS. As a last resort.

Honestly this is way over my head. :(

**Comment by rokobuljan** [comment] 2022-12-14 16:38
@skyfighteer In the end... The Mouse pan + scale is fixed with #3 to have no animations. (For now)
It's so rare someone will use both simultaneously that I don't see it worth the time to implement.

**Closed as completed by rokobuljan** 2022-12-14 16:38 UTC
Labels: minor

**Comment by skyfighteer** [comment] 2022-12-14 18:20
Great! Microsoft solved it the same way as you did with the built-in windows 11 image viewer :)

**Comment by rokobuljan** [comment] 2022-12-15 10:10
Indeed, nicely found @skyfighteer  
Not that I feel better about it but... yeah :)
